# Generated by Django 5.0.6 on 2024-06-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('veg_meat', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('center', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.event')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsOfStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arriving', models.DateField()),
                ('time_of_arriving', models.CharField(max_length=100)),
                ('stay_overnight', models.CharField(max_length=100)),
                ('departure', models.DateField()),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.registrantdetails')),
            ],
        ),
    ]
